[server]
  bind_host = "localhost"
  bind_port = 9000
  url_scheme = "http"
  url_hostport = "geo.kralidis.ca"
  url_basepath = "/jivan/"
  default_mimetype = "application/json; charset=UTF-8"
  encoding = "utf-8"
  language = "en-US"
  pretty_print = true
  paging_limit = 10
  paging_maxlimit = 1000

[logging]
  level = "INFO"
  #logfile = "/tmp/jivan.log"

[metadata]
  [metadata.identification]
    title = "jivan"
    description = "jivan is a Go server implementation of OGC WFS 3.0"
    keywords = [ "geospatial", "features", "collections", "access" ]
    keywords_type = "theme"
    fees = "None"
    accessconstraints = "None"
    [metadata.provider]
      name = "Organization Name"
      url = "https://github.com/go-spatial/jivan"
    [metadata.contact]
      name = "Lastname, Firstname"
      position = "Position Title"
      address = "Mailing Address"
      city = "City"
      stateorprovince = "Administrative Area"
      postalcode = "Zip or Postal Code"
      country = "Country"
      phone = "+xx-xxx-xxx-xxxx"
      fax = "+xx-xxx-xxx-xxxx"
      email = "you@example.org"
      url = "http://example.org"
      hours = "Hours of Service"
      instructions = "During hours of service.  Off on weekends."
      role = "pointOfContact"

[providers]
  data = "test-data/athens-osm-20170921.gpkg"
